matcher:
  key: ^_ymlex_\[(?<actual_key>.*)\]$
  level:
    min: 0
    max: -1

solvers:
  bitwarden:
    type: bash
    location:
      file: https://raw.githubusercontent.com/tidunguyen/ymlex/main/solvers/bitwarden/script.sh
