matcher:
  key: ^_ymlex_\[(?<actual_key>.*)\]$
  level:
    min: 2
    max: -1
solvers:
  bitwarden:
    type: bash
    location:
      file: https://raw.githubusercontent.com/tidunguyen/ymlex/main/solvers/bitwarden/script.sh
  aws:
    type: binary
    args:
    - -o=yaml
    location: s3|http|git|local
  my-custom-solver:
    type: bash
    inline: |
      world
