#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all
#@overlay/match-child-defaults missing_ok=True
#@overlay/match-child-defaults expects="0+"
---
matcher:
  level:
    max: 3

solvers:
  aws:
    type: binary
    args:
      - -o=yaml
    location: s3|http|git|local
  
  my-custom-solver:
    type: bash
    inline: |
      world
